language: java

sudo: false
dist: trusty

before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk-ea

